### ISSUE TITLE
报空

### ISSUE THREAD

**Issue by zhuhc1991** [subchen/jetbrick-template-2x-samples#1]
最近用2.0.6版本的，模板渲染报空指针，实在想不明为啥，神奇的是同一个模板内容，有的渲染没问题，有的渲染却报空指针。以下是报错信息：
java.lang.NullPointerException
        at jetbrick.bean.asm.delegate.java_lang_String.getField(Unknown Source)
        at jetbrick.bean.FieldInfo.get(FieldInfo.java:135)
        at jetbrick.template.parser.ast.AstText$Jdk7CharArrayEncoder.<init>(AstText.java:261)
        at jetbrick.template.parser.ast.AstText.execute(AstText.java:212)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
        at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
        at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
        at com.asiainfo.womail.nc.common.util.TemplateUtil.renderWithContent(TemplateUtil.java:45)
        at com.asiainfo.womail.nc.common.manager.AbstractTemplateManager.render(AbstractTemplateManager.java:75)

**Comment by subchen** [comment]
应该是和这个bug有关系：https://github.com/subchen/jetbrick-commons/issues/4
建议升级 jetbrick-template 和 jetbrick-commons 到最新版本

**Comment by zhuhc1991** [comment]
那为啥同一个模板，有的渲染没问题，有的却报空呢？？

**Comment by subchen** [comment]
几次出错是同一个地方吗？
能否给出错误时候打印出的模版错误位置吗？

**Comment by zhuhc1991** [comment]
就是错误时候没打印出的模版错误位置，就直接报空了，有20万的请求，就是一小部分报这个错误，其他几十万都没问题

**Comment by zhuhc1991** [comment]
模板内容是：【xxxx】恭喜！您获得1000000元意外保险，请马上领取！戳 ${sl(L)}【xxx邮件提醒】
上下文：{"L","xxxx"}

**Comment by subchen** [comment]
不知你用到jdk 版本是多少？ openjdk 7+ or oraclejdk 7+ ?

目前`JetTemplate`有2个APIs
```
public void render(Map<String, Object> context, Writer out);
public void render(Map<String, Object> context, OutputStream out);
```
看上去你应该用的第一个带`Writer`的，或者你可以改成用第二个API，这个API不会进入到目前会出错的代码。当然还是建议升级一下 jar 包。

**Comment by subchen** [comment]
目前看下来，这个地方可能存在并发问题：
https://github.com/subchen/jetbrick-template-2x/blob/master/jetbrick-template/src/main/java/jetbrick/template/parser/ast/AstText.java#L207-L217

你的20W并发，出错的应该是前几个request吧？应该没有中间的request报错吧？如果是这样的话，可能就是并发问题了，需要保护一下。

**Comment by zhuhc1991** [comment]
用的是jdk7
比较神奇的是，测试环境，本地环境都没法重现，就只有现网才报这个错误，看来，好像是分散的报错，前，中都有呢~~~~(>_<)~~~~
O(∩_∩)O谢谢

**Comment by subchen** [comment]
如果在现网很容易重现的话，我更可以给你编译一个新的jar让你帮忙测试一下，看看能不能解决并发问题

**Comment by zhuhc1991** [comment]
嗯嗯，现网是很容易重现。。。那麻烦你了O(∩_∩)O

**Comment by subchen** [comment]
我build了2个版本的jar
- 2.0.6: https://dl.bintray.com/subchen/download/jetbrick-template-2.0.6-modified.jar
- 2.1.4: https://dl.bintray.com/subchen/download/jetbrick-template-2.1.4-modified.jar
如过用2.1.4 最新版本的话，需要下载最新的 jetbrick-commons 版本

你帮忙测试一下吧

**Comment by zhuhc1991** [comment]
嗯嗯，好的
O(∩_∩)O谢谢
